version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: vacancy_service_db
    environment:
      POSTGRES_DB: vacancy_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - vacancy-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: vacancy_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8082:80"
    networks:
      - vacancy-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  vacancy-network:
    driver: bridge